### ISSUE TITLE
bulk parsing - handle sparse columns?

### ISSUE THREAD

**Issue by derekeder** [datamade/usaddress-api#4]
Related to #2 

Parsing the dedupe [CSV example data of early childhood locations](https://github.com/datamade/dedupe-examples/blob/master/csv_example/csv_example_messy_input.csv) works!

Results: https://docs.google.com/spreadsheets/d/1t0d9N3C4SNXotNUf5PzP9MhgMQ_mJ8EVnqV-QnizZfI/edit#gid=590495458

However, it creates 20 columns, most of them sparsely populated:

* AddressNumber
* StreetNamePreDirectional
* StreetName
* StreetNamePostType
* StreetNamePostDirectional
* OccupancyIdentifier
* SubaddressType
* SubaddressIdentifier
* OccupancyType
* StreetNamePreType
* PlaceName
* USPSBoxType
* USPSBoxID
* StateName
* ZipCode
* IntersectionSeparator
* SecondStreetName
* Null (fixed in https://github.com/datamade/usaddress/issues/80)
* BuildingName
* Recipient

Should we stick with this output, or consider consolodating sparse columns into one?

**Comment by fgregg** [comment]
Don't include the Null column all together. Then, remove all empty columns. I bet that will be enough.

**Comment by derekeder** [comment]
@fgregg the columns exist because at least one of the 3,000+ addresses had a tag of that type.

**Comment by fgregg** [comment]
k. I think we should return it all.

**Comment by derekeder** [comment]
Flagging this as a feature, not a bug
